<?php

declare(strict_types=1);

use JohnWink\FilamentLeadPipeline\Support\ImmoScoutOAuthSigner;

/*
 * Reference signature generated by the standalone OAuth 1.0a client that was
 * verified live against the ImmoScout24 sandbox (request_token, access_token
 * and lead retrieval all returned HTTP 200).
 */

it('produces the verified HMAC-SHA1 signature for a fixed nonce and timestamp', function (): void {
    $signer = new ImmoScoutOAuthSigner();

    $header = $signer->authorizationHeader(
        method: 'GET',
        url: 'https://rest.sandbox-immobilienscout24.de/restapi/api/financing/construction/v2/lead',
        queryParams: ['from' => '2026-04-04T00:00:00', 'to' => '2026-07-03T12:00:00'],
        consumerKey: 'test-consumer-key',
        consumerSecret: 'test-consumer-secret',
        token: 'test-access-token',
        tokenSecret: 'test-token-secret',
        nonce: 'fixed-nonce-123',
        timestamp: 1783100000,
    );

    expect($header)
        ->toStartWith('OAuth ')
        ->toContain('oauth_consumer_key="test-consumer-key"')
        ->toContain('oauth_token="test-access-token"')
        ->toContain('oauth_signature_method="HMAC-SHA1"')
        ->toContain('oauth_timestamp="1783100000"')
        ->toContain('oauth_nonce="fixed-nonce-123"')
        ->toContain('oauth_version="1.0"')
        ->toContain('oauth_signature="' . rawurlencode('ZmVuVDHZYrylNctqDse5PxTg+Xs=') . '"');
});

it('signs requests without an access token for two-legged calls', function (): void {
    $signer = new ImmoScoutOAuthSigner();

    $header = $signer->authorizationHeader(
        method: 'GET',
        url: 'https://rest.sandbox-immobilienscout24.de/restapi/api/financing/construction/v2/lead',
        queryParams: ['test' => 'true'],
        consumerKey: 'test-consumer-key',
        consumerSecret: 'test-consumer-secret',
    );

    expect($header)
        ->toStartWith('OAuth ')
        ->toContain('oauth_consumer_key="test-consumer-key"')
        ->not->toContain('oauth_token=')
        ->toContain('oauth_signature="');
});

it('generates unique nonces when none is provided', function (): void {
    $signer = new ImmoScoutOAuthSigner();

    $headers = collect(range(1, 5))->map(fn (): string => $signer->authorizationHeader(
        method: 'GET',
        url: 'https://rest.immobilienscout24.de/restapi/api/financing/construction/v2/lead',
        queryParams: [],
        consumerKey: 'key',
        consumerSecret: 'secret',
    ));

    $nonces = $headers->map(function (string $header): string {
        preg_match('/oauth_nonce="([^"]+)"/', $header, $matches);

        return $matches[1];
    });

    expect($nonces->unique())->toHaveCount(5);
});
